### ISSUE TITLE
Enable additional result types

### ISSUE THREAD

**Issue by egoes401** [pulibrary/ExcelAlmaLookup#14]
This is a really useful tool. Is it possible to have as many/equivalent Result Types as Fields to Search? 

In my case, I would like to search by MMS ID and get a result for Material Type (alma.mms_material_type). Currently it looks like I could search **for** material type but not get it as a search result. 

Thank you, 

Evelyn Goessling
UC Irvine Law Library

**Comment by tventimi** [comment]
Hello Evelyn,

Thanks for your message.  I am the developer of this tool.  I am actually on vacation this week but can definitely look into this more when I get back next week.  I wanted to just confirm that you are asking about the material type of the Physical Item records, rather than the bib record (i.e. position 6 of the Leader field).  Unfortunately (and strangely), the SRU integration can search certain fields that it does not necessarily return, but I can see if the item material type is retrievable in some way.

Tom Ventimiglia 
Princeton University Library

**Comment by egoes401** [comment]
Tom,

Thanks for your message.

I wanted to just confirm that you are asking about the material type of the Physical Item records, rather than the bib record (i.e. position 6 of the Leader field).
I made a mistake - It's actually the bib record resource type that I am after.

I considered writing an excel formula to read the Leader and 008 fields to get this info, but I am not very experienced with creating complex formulas like that, hence my suggestion to add it to the tool.

Thanks again for creating this fantastic tool. My query is not urgent so please enjoy your vacation!

Evelyn

Evelyn Goessling
Electronic Resources & Metadata Law Librarian | Law Library
University of California * Irvine | School of Law
401 E. Peltason Dr., Suite 2000 | Irvine, CA  92697-8000
949.824.3644 | ***@***.******@***.***>

**Comment by tventimi** [comment]
Hi Evelyn,

You can set the result type to extract a specific substring of a field.  For example, the result type "Leader(6,2)" will extract 2 characters from the Leader field starting as position 6 (i.e. characters 6 and 7, the record type and bib level).  You can do something similar with the 008 - i.e. "008(35,3) will extract the 3 characters starting at position 35 (i.e. the language code).  Would that approach get you the information you are looking for?

Tom

**Comment by egoes401** [comment]
Hi Tom,

Yes, that would definitely work. Thanks for the suggestion!

Evelyn

**Comment by tventimi** [comment]
OK great!  I am going to close this ticket, but feel free to reach out with any other questions or suggestions.

Tom
