### ISSUE TITLE
Retrieve location of specific barcode, not all locations

### ISSUE THREAD

**Issue by MicheleCombs** [pulibrary/ExcelAlmaLookup#15]
When I run a barcode lookup and ask for "Location" as the desired result to return, it returns the locations for ALL holdings associated with the matching item's parent bib record.  Since a barcode can only have a single location, it would be very desirable to have the option of returning either (a) the location (the 852) for _only the parent holding record_ or (b) the value of "Permanent location" in the item record.

For example, let's say I have a bib record with 2 holdings records, MFHDA which has location spec_man and MFHDB which has location sulf_spec.  
I have a barcoded Item 32911058647310 which has a Permanent location of SULF and is linked to holding MFHDB.  
When I run the barcode lookup, I get this:  sulf_spec¦spec_man   
I would rather get just sulf_spec (the MFHDB location) or SULF (the item's Permanent location).

Thank you for considering!

**Comment by MicheleCombs** [comment]
I do see that "alma.permanentPhysicalLocation" is an option in the "Fields to search" dropdown, but it isn't in the "Result types" drop down.

**Comment by tventimi** [comment]
Hi Michele,

Thanks for reaching out - the feature you suggest would definitely be useful in general.  I think it may be possible to implement this, but it would require enabling a certain setting in your SRU integration.  Would you or your admin be able to activate "Holdings Options (ISO 20775)", as described in the documentation below?

https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/030Resource_Management/190SRU_SRW_Search

This option would make some more detailed holdings information visible, such as barcodes and their associated locations.   Even with this feature enabled, I would need to update the plugin to only return locations connected to a specific barcode, but this functionality could be included in an upcoming release.

Interestingly, although the SRU integration allows searching by many different fields, the results it returns are more limited when it comes to holdings and items.  Of course, if the information you are looking for happens to be stored elsewhere in the bib record (a 9xx field for example), you could also extract it by entering that field or subfield code as a "result type"

Tom Ventimiglia
Princeton University Library

**Comment by MicheleCombs** [comment]
Thank you!  I've made the request to our IT folks, with rationale.  Will let you know what they say.

**Comment by MicheleCombs** [comment]
Hm.  If I do a search on barcode, with result type set to *Location/DBName from the drop-down, I get both “scrc” and the sublocation – see screen cap below.  Does that help?

***@***.***

**Comment by tventimi** [comment]
Hi Michele,

I think github removed the screenshot you sent, but I understand what you are describing.  Is the "scrc" library code equivalent to the library name "Bird Special Collections"?  

Of course, it would be ideal to be able to retrieve both the library and location code, either as codes or full names.  I'll try to make this happen.  It is just a matter to matching up data from two different sources, so I wanted to confirm that the library code and name are indeed a match.  Thanks for your patience with this.

Tom

**Comment by MicheleCombs** [comment]
![screencap](https://github.com/user-attachments/assets/85e6c608-3292-4365-865f-6d9dbda506ef)

**Comment by MicheleCombs** [comment]
Yes, I believe the code "scrc" has the label Bird Library pecial Collections - added screencap above

**Comment by tventimi** [comment]
Ok great, I can see it now.  I'll look into this more and keep you posted.  Thanks for your help!

**Comment by tventimi** [comment]
Hi Michele,

I just wanted to let you know that I released a new version of the plugin today (v1.3.0).  Now, if a user searches by barcode, and includes item-specific fields such as location, shelf locator, etc., the results will only include those values tied to that specific barcode/item.  

For simplicity, I am including the version of the fields found in the ISO holdings output, which uses a full name (e.g. "Bird Special Collections") for the library name, and the code (e.g. "sulf_spec") for the location.  This is just a quirk of the ISO holdings format, but doing this way is a little less error-prone than trying to map the library/location codes and names.  Still, let me know if there is a use case where a different format would be better.

We never received an answer from Ex Libris about the case where a holdings has more than 100 item records.  So, this problem is not resolved, but I have noted it in the documentation.  As you suggested, it is likely an edge case, and it is still worth adding the feature with that caveat.

Thanks again for all your helpful feedback and suggestions!

Tom

**Comment by MicheleCombs** [comment]
Fantastic, thank you!  Will get it installed asap :)

Michele
