### ISSUE TITLE
Suggestion: decode HTML entities in results

### ISSUE THREAD

**Issue by sbdli** [pulibrary/ExcelAlmaLookup#4]
Fantastic tool! We've edited the VBA LookUp dialog code locally to replace specific characters - so decoding HTML entities in results (by default or optionally) may be a useful enhancement for other users as well.

Two common examples:
Barcodes: return ">" instead of "&gt;"
Titles: return "&" instead of "&amp;"

Thanks!

**Comment by tventimi** [comment]
Thanks for the suggestion! I will definitely look into that feature. Could you please point me to one or two records from your institution's catalog where the tool returns HTML entities, so I can include them in my testing?  Thank you.

Tom Ventimiglia
Princeton University Library

**Comment by tventimi** [comment]
I believe this issue should be fixed in v1.1.2 of the tool, just released today.  Please try it out and let me know if it works for you.  If there are any other issues with decoding HTML entities, please feel free to reopen this ticket and provide examples.  Thanks for your feedback and interest in this tool!

Tom

**Comment by sbdli** [comment]
Looks good - thanks for the fix and for your continued work on this tool, it's much appreciated by our library staff!
Sarah, UNSW
